pipeline {
    agent any
    tools {
        nodejs 'node14'
    }
    stages {
        stage('Build') {
            steps {
                echo "Ejecutar npm install" 
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                echo "Ejecutar npm test" 
                sh 'npm test'
            }
        }
    }
}
